name: Stable Build
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
      
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Project
      run: msbuild FfmpegConverter.sln /t:Build /p:Configuration=Release
    - name: Release
      uses: softprops/action-gh-release@v2.2.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/Release/FfmpegConverter.exe